# v3
# file: k8s/aggregator/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
spec:
  replicas: 1
  selector:
    matchLabels: { app: aggregator }
  template:
    metadata:
      labels: { app: aggregator }
    spec:
      containers:
        - name: aggregator
          image: aggregator:latest
          args: ["-props","/app/aggregator.properties"]
          volumeMounts:
            - name: props
              mountPath: /app/aggregator.properties
              subPath: aggregator.properties
      volumes:
        - name: props
          configMap:
            name: aggregator-props
