// v1
// k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger
  labels:
    app: ledger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger
  template:
    metadata:
      labels:
        app: ledger
    spec:
      containers:
        - name: ledger
          image: ledger:latest
          imagePullPolicy: IfNotPresent
          args: ["-addr", ":8083", "-data", "/data", "-logs", "/logs"]
          ports:
            - containerPort: 8083
          volumeMounts:
            - name: ledger-data
              mountPath: /data
            - name: ledger-logs
              mountPath: /logs
      volumes:
        - name: ledger-data
          emptyDir: {}
        - name: ledger-logs
          emptyDir: {}
