// v1
// k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ledger
  labels:
    app: ledger
spec:
  selector:
    app: ledger
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
  type: ClusterIP
