# v2
# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mape-config
  namespace: nrgchamp
data:
  mape.properties: |
    # v2
    zones=zone-a,zone-b
    target=22.0
    hysteresis=0.5
    fan.steps=0.3,0.7,1.2,2.0
    fan.speeds=25,50,75,100
