# v2
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mape
  namespace: nrgchamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mape
  template:
    metadata:
      labels:
        app: mape
    spec:
      containers:
        - name: mape
          image: mape:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: "kafka:9092"
            - name: AGGREGATOR_TOPIC
              value: "aggregator.to.mape"
            - name: ACTUATOR_TOPIC_PREFIX
              value: "zone.commands."
            - name: LEDGER_TOPIC_PREFIX
              value: "zone.ledger."
            - name: LEDGER_MAPE_PARTITION
              value: "1"
            - name: PROPERTIES_PATH
              value: "/app/configs/mape.properties"
            - name: POLL_INTERVAL_MS
              value: "250"
            - name: LOG_DIR
              value: "/app/logs"
          volumeMounts:
            - name: config
              mountPath: /app/configs
              readOnly: true
            - name: logs
              mountPath: /app/logs
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
      volumes:
        - name: config
          configMap:
            name: mape-config
        - name: logs
          emptyDir: {}
