# v0
# k8s/gamification/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamification
  template:
    metadata:
      labels:
        app: gamification
    spec:
      securityContext:
        runAsUser: 10001
        runAsNonRoot: true
      containers:
        - name: gamification
          image: nrgchamp/gamification:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: gamification-config
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /health
              port: 8086
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8086
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: data
          emptyDir: {}
